### ISSUE TITLE
Unintended report but already validated

### ISSUE THREAD

**Issue by skyonedot** [Increment-Finance/sybil-hunting#1]

**Comment by louie-ml** [comment]
Thank you for your report @skyonedot. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) proves that these addresses indeed belong to the same entity/person.

![image](https://user-images.githubusercontent.com/80497604/219203557-50406e11-5cac-4be8-ae2e-145aeb6b0b38.png)


The following 4 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0xabc67a49d7d75bd04fa1dae22cd4b8c4f796540a
0x7a4c8e3655d665f3e25ccd6b60b1b024629b3705
0x75d25dfffff585b83b3f535b6ecad842fae3edd2
0x4e3e782053e560fdebd2be4a6c9a1f26c9a0faa4
```

And the following 1 address will remain

`0x0fe805304e49e993b2c59287000a2726330d2055`
