### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by cccggg123** [Increment-Finance/sybil-hunting#2]
# Sybil Addresses
0xe1Fcb0b4A77d931A3A806E7F6a8DebfaDa6fa1c4
0x2CDc61E9eA6E9c833704c7A81Cb12a72fA540d69
0x87434b593481F0b7Dd61E6670087f17d731c5D34
0x7E5CAE89Ef2Ea9067eDDAD0a8BdBc2D357ca7673
0x4d5Aa902BAbd98a54d2c69EEA54f32bea54646b3
0x216065a3688295Dc8A0C5f144aB6fFf5cD0a8818

# Reasoning
fee transfer   ，same time, same operation

# My Address (Optional)
0x27ee28301f455AD1532F78d3C075Dd826f872176

**Comment by louie-ml** [comment]
Thank you for your report @cccggg123. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows two paths in the transfer flows and does not show a circular pattern.

![image](https://user-images.githubusercontent.com/80497604/219418552-7ddc0955-a4ae-4d14-8f27-663b90b4f67c.png)

**Comment by cccggg123** [comment]
Interact with the project's contract,
transfer gas to each other
are on the reward list

louie-ml ***@***.***> 于2023年2月17日周五 00:14写道：
