### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by cccggg123** [Increment-Finance/sybil-hunting#3]
# Sybil Addresses
0xABB194541D37E9e7413A6B08fDe878Ae753e904b
0x90780384894086B4Cfb015dAd053c49C4b4120ae
0xd96d580c50F542AA192E255C52A8c82CFb9206a1
0x599138121c0E29FEd8a9ad985B620c054E989233
0x2D4D91c6707743E5329ccE93073bbcE8190ce57C
0x847c086ef7796fb39C22600dcAA683B5a7a4c8AB
0x675a98a78e9d35142E5f4Aa17921F74671E939aA
0x0997c8B1bA24622560682d71EE4018288568bA28
0xFD77E21Bfdb499Df53c484f1F8A473660Aa580A1
0xd02b70D77335442BFC125E3f4547B5AA4d2411E8
0x4aA7aA67801db508BF670b07385F9Baf865bF5a6
0xA30aD1c64d2f3504B632b256CCCABe3D72bACB20
0x212e3C657Ad843BE09745d78331Cab3CAa170563
0xc5b98fDB03d32d176D9D471F270D2dB72E377C21
0x7499f2bB0E325166aCc3b2403f8EB57259a6f9c8
0xC9F8eDD08888f8d026C9205B55934dFeaeef2Aa2

# Reasoning
transfer between accounts（test fees)
# My Address (Optional)
0x27ee28301f455AD1532F78d3C075Dd826f872176

**Comment by louie-ml** [comment]
Thank you for your report @cccggg123. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows that a group of these addresses indeed belong to the same entity/person.

![image](https://user-images.githubusercontent.com/80497604/219425505-a195654b-a97c-424e-a69f-f2ce735c0533.png)

The following 13 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0xABB194541D37E9e7413A6B08fDe878Ae753e904b
0x90780384894086B4Cfb015dAd053c49C4b4120ae
0x599138121c0E29FEd8a9ad985B620c054E989233
0x2D4D91c6707743E5329ccE93073bbcE8190ce57C
0x847c086ef7796fb39C22600dcAA683B5a7a4c8AB
0x675a98a78e9d35142E5f4Aa17921F74671E939aA
0x0997c8B1bA24622560682d71EE4018288568bA28
0xFD77E21Bfdb499Df53c484f1F8A473660Aa580A1
0xd02b70D77335442BFC125E3f4547B5AA4d2411E8
0x4aA7aA67801db508BF670b07385F9Baf865bF5a6
0xA30aD1c64d2f3504B632b256CCCABe3D72bACB20
0x212e3C657Ad843BE09745d78331Cab3CAa170563
0xc5b98fDB03d32d176D9D471F270D2dB72E377C21
```

And the following 3 addresses will remain

```
0x7499f2bB0E325166aCc3b2403f8EB57259a6f9c8
0xC9F8eDD08888f8d026C9205B55934dFeaeef2Aa2
0xd96d580c50F542AA192E255C52A8c82CFb9206a1
```
