### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by 0xAnhlabs** [Increment-Finance/sybil-hunting#4]
# Sybil Addresses
0x000000000000000000000000000000000000dead
0x000003e526773aed954ecacff76f857aa4f43fb5
0x0095814c34d18fbbd2171eb57d5a2d71d6f6fed5
0x00bc581c132a74e19b7745fc4d62880733a058fb
0x00d4853399214b9fea3e93a668e984d5964cd839
0x0131ec2b30f9bf2f1079368efe73e2e462880aad
0x02162532c519bc1b31fd7670475b3e4e0701c90d
0x0325e02f0006f0b68b2289bafccdaed46878dbd7
0x0411b58fb1277d16085b88a2f215592139323e7e
0x04ac4cb728a7b6a510295d167b76d59f9c27d274
0x04b63ca298abb7b77f37d1d4d6210851f77c11e4
0x057f3f6151b324b4dd6fd0d24425dd6db1bdda15
0x0690a6ff42f38e907b06e12dd285c58f0f053f78
0x089d819ac3cc9eb93e865ad0ab08b520017b8f37
0x098c74229d27801a7054bad155075f49fd6d6161
0xbafabe064efa028b79ff690331d1038d4948c11f 
0x0a2bf0edaf422d51c115d781fc7fdf75baba27de
0x0a6b6953a9fe4df93642822e53ab3fe015875cad
0x0c45271a86e9fd97da833cd9e5ae634547e1ba7d
0x105a11eb17c362f38b0a59c67a1c71c0e4424e15
0x11a2cd1ef6da1733ec1e9bc44f74d3eac71a4572
0x126f421ae26eacd7a672d908d24ce3528d002114
0x13911dfcbec8e72ef1d3855a7ae5d2f9a3775aa9
0x14c86d65b37d33b1209893f843f625f865c257b6
0x150df654711630b8f161d961027dd1f5111c640b
0x15222b73cd726fb3fa64aa3c1b829e78ec00e1eb
0x15712cd4daa7a9e830fec64f86764bbca5ee16b0
0x15cb2d8cde03ff50b8dd6cc39932576f20e742c4
0x16ced6237bf6e334024708b0e903a2198b1b5624
0x18eded85e384dffb9f24ecc02a0ea0ca88728eb4
0x19d43f06267546d91d3dc45716aa21bbd9076c59
0x1a1b9952d7ffad9c5786a55a4807e680fd9255a5
0x1afce2119455882de0142f54f88205b7b0101088
0x1ce4a4037c160aa5f4ea5a5bce6f3605cafb0234

# Reasoning
- Burn Address 
- Less transactions
- No transactions (Only 1 transaction received poap)
- Wallet assets under $0.5
- Same transaction and wallet creation date 

# My Address (Optional)
0x66d692bBeCAcAe3026834750e603291Fe4384161

**Comment by louie-ml** [comment]
Thank you for your report @HankCrypto. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) cannot provide much information looking at its activity on Ethereum mainnet, but many of these addresses supposedly took part in Beta v1. After checking data on Rinkeby etherscan, many addresses did not interact with the Increment smart contracts nor had any transaction history.
![image](https://user-images.githubusercontent.com/80497604/219531525-986ce549-e81e-4d76-b9c4-9b18bd0e82a3.png)

The following 16 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0x000000000000000000000000000000000000dead
0x000003e526773aed954ecacff76f857aa4f43fb5
0x0131ec2b30f9bf2f1079368efe73e2e462880aad
0x02162532C519bc1b31Fd7670475B3E4E0701C90d
0x0325e02f0006f0b68b2289bafccdaed46878dbd7
0x0411b58fb1277d16085b88a2f215592139323e7e
0x0690a6ff42f38e907b06e12dd285c58f0f053f78
0x089d819ac3cc9eb93e865ad0ab08b520017b8f37
0x0c45271a86e9fd97da833cd9e5ae634547e1ba7d
0x13911dfcbec8e72ef1d3855a7ae5d2f9a3775aa9
0x14c86d65b37d33b1209893f843f625f865c257b6
0x150df654711630b8f161d961027dd1f5111c640b
0x15222b73cd726fb3fa64aa3c1b829e78ec00e1eb
0x18eded85e384dffb9f24ecc02a0ea0ca88728eb4
0x19d43f06267546d91d3dc45716aa21bbd9076c59
0x1afce2119455882de0142f54f88205b7b0101088
```

And the following 18 addresses will remain
```
0x0095814c34d18fbbd2171eb57d5a2d71d6f6fed5
0x00bc581c132a74e19b7745fc4d62880733a058fb
0x00d4853399214b9fea3e93a668e984d5964cd839
0x04ac4cb728a7b6a510295d167b76d59f9c27d274
0x04b63ca298aBb7B77F37d1D4D6210851f77c11E4
0x057F3F6151b324b4dD6Fd0d24425dd6dB1BDda15
0xbafabe064efa028b79ff690331d1038d4948c11f
0x0a2bf0edaf422d51c115d781fc7fdf75baba27de
0x0a6b6953a9fe4df93642822e53ab3fe015875cad
0x105a11eb17c362f38b0a59c67a1c71c0e4424e15
0x11a2cd1ef6da1733ec1e9bc44f74d3eac71a4572
0x126f421ae26eacd7a672d908d24ce3528d002114
0x15712cd4daa7a9e830fec64f86764bbca5ee16b0
0x15cb2d8cde03ff50b8dd6cc39932576f20e742c4
0x16ced6237bf6e334024708b0e903a2198b1b5624
0x1a1b9952d7ffad9c5786a55a4807e680fd9255a5
0x1ce4a4037c160aa5f4ea5a5bce6f3605cafb0234
0x098C74229D27801a7054BAD155075F49fD6D6161
```
