### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by lilianlecter** [Increment-Finance/sybil-hunting#43]
# Sybil Addresses
0x1ed45d59730a91011e17c039e2491f332c9d571d
0x098f1a48c3080c0488e77fa19e495d76a55aa1ec
0xba137a4287c81b0221ce57b274361b6e15df614d
0x1bd8f4f7a34aeda6bd9902735b00af7756e9f0c9
0xd3462632590af95b762d4ce7d745887d56aabf8d
0xc8a2d77e024c3b489c6715d3b2a2c21a68717422
0xbfbb7acbecbe46ed82aad614fa3d735f3ee54a4f
0xeb394954d312351d5d055b0fa2af3fdb2f210597
0x86e663d792b262f342cd98d8d4fee16a99123975
0xaaa6d167a8e229a53222439e0ada7c655559c7df
0x7d6c539282a9bcd60c4a8b27f33692c2b4c15cda
0x1e95134d0b78d68bf9ec30512b1c21d35c1d613a
0xd34a68f30f806b823c3341686785f62af859327a
0x34b36b44b853236e49998ec68a08ea4a2c7b6515
0x5083e86b5ef007dd8e1eceefee6f370133c9eec0
0x5b216a679ae9df733d614d64fc33da7c157cdf8d
0xd9814c30e51d963fc9a860e5a066a785e3c6e83a
0xd7a424d2df717a0e2cd3c621de95f2a7fe6bd27f
0x4ac343fa42d82f849bf871406933ac3afd84d5b0
0xc879041d2658ceb79d42f444b19e7511c44c5339
0x5c12d52a8f08a7c1696d93bda670e76ae9e827f8
0x1ef237d0a8964f2c67848465f56fbd7de29255d4
0x6ddeb6fbce41348c9865cc7e7b8e9aa3b83c1a56
0x8896c44f529989384ba9feea3c1c843139bdaa81
0xac09e4cdddbca163f6d7142589a40ca5efd06521
0xfcc262a5dc472c382283594a395eeca53ac4d18b
0x5df895965f2cf9422f4b85eec7bb96a5243f3429
0xcca675f6395e0b947be88c28883e886987dd0c4b
0xf58870066a0c595de08191f2c2f6cfe0afc8387a
0x8cfb0527bf5451fe1a431957b897b7828bf2aced
0x9c7738c761b7dac9b2eb298339ac60a59ad6d71d
0x43893b41f3cae588dadd77fed24d7e682b9bd172
0xd671a9a25759f7a3f05fc2cb3d817257400e8f1b
0x58b6dd473c352a591d7373d54887f25842ad6d36
0x68bf9172062bbe1710655bd0532db0e225faa2ec
0x59aa8d606bb6e9dbceb7a570a4d0c2674ba8caff
0x3825f1c3026df73fafc2412d1c97d2d5c196f75f
0x383807be99bf491010a65af0f6e7170381053d20
0xd376710580e4460c86e6e3d36979cd84ab3a7f1c
0x38eae7074a99a42394a3539b52cfd670de0c3953
0x8a2aa78c8d0f9eeaaeaba788e3747f5336324036
0x87cdceccd4683e00c010ed4b3f99714f4227590d
0x5ff2c3f97217aba75a66e9d299f5810c99b8b6d6
0x40258b0731631fb9d00169236353c9104235efd5
0xb1d0657e4902891e5c4cf002be441328e1da1145
0x2503d115b60c0542ce419621eb05c5c5d7d1fcb5
0x90d7c3ba6b06ecd0d50239ce20e80ec9badd20e3
0x2c5177cc460d003fd013570ee5e21da6ec09294a
0x2189c94de39b2f48adda4efe66c844d6dda6cb42
0xd11f64efc3793a6b69e9292963809f8dfbbe11d7
0x5637584843a6b7b2830fc5e3e407d6a8d47c66bc
0x0bb77e150d8c2e7023848016c4407b33b5bbb55f
0x26300d335192ded23d312e1bd449a06587b9b672
0xde3b44b8cc81229c51200f8671b3f4c5c1826d08
0x5dc906f9aa4f0d93cbf8234e8d71e1d142cd1112
0x75e15acfcf9a89fae6fc8f0284eba2702a2e436d
0x02a4eb7f4cb37b9ababd1b5aa4290386688be627
0xf6664eb49f1905974b9e9e7441589752ae716347
0x228f7bf0dfecd44ac3a7ee50104ecc7321fa0646
0xb4234c56499eea0dc5643c5bf4bf9ba4cd083632
0x1b0c647a76ad354b8ba8b694e9be72c349a08cc6
0x7816407b6545b81afae860d0f17c5e0dc0531cb7
0xa18d35901d35fd7a680dbe2df681cb14f3746dd8
0xa60a0741711fa8c3672cf6dfb0ea46ea4a16cbf2

# Reasoning
There are multiple and recent transfers of $MATIC between addresses.

# My Address (Optional)
0x6fF94501F7Df2201CcB0ecFF9a5e8c087FfbAc8f

**Comment by louie-ml** [comment]
Thank you for your report @lilianlecter. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows a strong connection between all the listed addresses. <img width="772" alt="image" src="https://user-images.githubusercontent.com/80497604/222290156-539082e8-d603-4642-b214-1f2a4bafe1cd.png">

The following 63 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0x1ed45d59730a91011e17c039e2491f332c9d571d
0x098f1a48c3080c0488e77fa19e495d76a55aa1ec
0xba137a4287c81b0221ce57b274361b6e15df614d
0x1bd8f4f7a34aeda6bd9902735b00af7756e9f0c9
0xd3462632590af95b762d4ce7d745887d56aabf8d
0xc8a2d77e024c3b489c6715d3b2a2c21a68717422
0xbfbb7acbecbe46ed82aad614fa3d735f3ee54a4f
0xeb394954d312351d5d055b0fa2af3fdb2f210597
0x86e663d792b262f342cd98d8d4fee16a99123975
0xaaa6d167a8e229a53222439e0ada7c655559c7df
0x7d6c539282a9bcd60c4a8b27f33692c2b4c15cda
0x1e95134d0b78d68bf9ec30512b1c21d35c1d613a
0xd34a68f30f806b823c3341686785f62af859327a
0x34b36b44b853236e49998ec68a08ea4a2c7b6515
0x5083e86b5ef007dd8e1eceefee6f370133c9eec0
0x5b216a679ae9df733d614d64fc33da7c157cdf8d
0xd9814c30e51d963fc9a860e5a066a785e3c6e83a
0xd7a424d2df717a0e2cd3c621de95f2a7fe6bd27f
0x4ac343fa42d82f849bf871406933ac3afd84d5b0
0xc879041d2658ceb79d42f444b19e7511c44c5339
0x5c12d52a8f08a7c1696d93bda670e76ae9e827f8
0x1ef237d0a8964f2c67848465f56fbd7de29255d4
0x6ddeb6fbce41348c9865cc7e7b8e9aa3b83c1a56
0x8896c44f529989384ba9feea3c1c843139bdaa81
0xac09e4cdddbca163f6d7142589a40ca5efd06521
0xfcc262a5dc472c382283594a395eeca53ac4d18b
0x5df895965f2cf9422f4b85eec7bb96a5243f3429
0xcca675f6395e0b947be88c28883e886987dd0c4b
0xf58870066a0c595de08191f2c2f6cfe0afc8387a
0x8cfb0527bf5451fe1a431957b897b7828bf2aced
0x9c7738c761b7dac9b2eb298339ac60a59ad6d71d
0x43893b41f3cae588dadd77fed24d7e682b9bd172
0xd671a9a25759f7a3f05fc2cb3d817257400e8f1b
0x58b6dd473c352a591d7373d54887f25842ad6d36
0x68bf9172062bbe1710655bd0532db0e225faa2ec
0x59aa8d606bb6e9dbceb7a570a4d0c2674ba8caff
0x3825f1c3026df73fafc2412d1c97d2d5c196f75f
0x383807be99bf491010a65af0f6e7170381053d20
0xd376710580e4460c86e6e3d36979cd84ab3a7f1c
0x38eae7074a99a42394a3539b52cfd670de0c3953
0x8a2aa78c8d0f9eeaaeaba788e3747f5336324036
0x87cdceccd4683e00c010ed4b3f99714f4227590d
0x5ff2c3f97217aba75a66e9d299f5810c99b8b6d6
0x40258b0731631fb9d00169236353c9104235efd5
0xb1d0657e4902891e5c4cf002be441328e1da1145
0x2503d115b60c0542ce419621eb05c5c5d7d1fcb5
0x90d7c3ba6b06ecd0d50239ce20e80ec9badd20e3
0x2c5177cc460d003fd013570ee5e21da6ec09294a
0x2189c94de39b2f48adda4efe66c844d6dda6cb42
0xd11f64efc3793a6b69e9292963809f8dfbbe11d7
0x5637584843a6b7b2830fc5e3e407d6a8d47c66bc
0x0bb77e150d8c2e7023848016c4407b33b5bbb55f
0x26300d335192ded23d312e1bd449a06587b9b672
0xde3b44b8cc81229c51200f8671b3f4c5c1826d08
0x5dc906f9aa4f0d93cbf8234e8d71e1d142cd1112
0x75e15acfcf9a89fae6fc8f0284eba2702a2e436d
0x02a4eb7f4cb37b9ababd1b5aa4290386688be627
0xf6664eb49f1905974b9e9e7441589752ae716347
0x228f7bf0dfecd44ac3a7ee50104ecc7321fa0646
0xb4234c56499eea0dc5643c5bf4bf9ba4cd083632
0x1b0c647a76ad354b8ba8b694e9be72c349a08cc6
0x7816407b6545b81afae860d0f17c5e0dc0531cb7
0xa18d35901d35fd7a680dbe2df681cb14f3746dd8
```

And the following 1 address will remain

`0xa60a0741711fa8c3672cf6dfb0ea46ea4a16cbf2`
