### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by dyilmaz34** [Increment-Finance/sybil-hunting#50]
# Sybil Addresses
0xfe592bdd3c53753e707d462f6a51da2ea0255777
0xd699986f5606a0b77e630d7645907c873b9a5d4e
0x4a227be1d4080e16c678d816f9fbfaff92fc6351
0x75059838c9f2a4ed255a933f6d462c9844de3b4a
0x1402cb6dba304113f22a71a8c6c5422d0a5f1c12
0x8df69cabf49759955de46fd9ba0f5c3a234e480a
0xcce89fbe9c73cafcb44a2ca8c31fece3c7ad0829
0xa207ffb4e7d647860249726e72e1b4e1239ad70c
0x8120c778141412627a3060521dcbf42c05fe24d8
0x5fa7e38bf45d593836bad2eb4d8b1ac2df30f0b3
# Reasoning
1- There are many $BNB transfers between wallets.
2- The onchain data analysis website metasleuth.io verifies and visualizes these transactions and shows them to us. Below is website for review.
3- https://metasleuth.io/result/bsc/0x5fa7e38bf45d593836bad2eb4d8b1ac2df30f0b3?source=01829d08-9cae-4f5d-9181-70de320d46cd
# My Address (Optional)
0xB1896758599A9F03f9E4798990F5B49aceDC7E88

**Comment by louie-ml** [comment]
Thank you for your report @dyilmaz34. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows the path of the transfers from one address to another with a cluster of addresses in between connecting the path.
![image](https://user-images.githubusercontent.com/80497604/226042832-89fe629e-0129-433e-8881-18676b490cfd.png)

The following 9 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0xfe592bdd3c53753e707d462f6a51da2ea0255777
0xd699986f5606a0b77e630d7645907c873b9a5d4e
0x4a227be1d4080e16c678d816f9fbfaff92fc6351
0x75059838c9f2a4ed255a933f6d462c9844de3b4a
0x1402cb6dba304113f22a71a8c6c5422d0a5f1c12
0x8df69cabf49759955de46fd9ba0f5c3a234e480a
0xcce89fbe9c73cafcb44a2ca8c31fece3c7ad0829
0xa207ffb4e7d647860249726e72e1b4e1239ad70c
0x8120c778141412627a3060521dcbf42c05fe24d8
```

And the following 1 address will remain

`0x5fa7e38bf45d593836bad2eb4d8b1ac2df30f0b3`
