### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by okkux** [Increment-Finance/sybil-hunting#54]
# Sybil Addresses
0x22a5ccd63f2c9910ef170a0ddee2688f9c792e3c
0x320b18b84fc5452045fc3e01ed4b748f4f31e477
0x9b8070918bc61903df86bd97e3820a003a2309f9
0x74cfa655e7f8d22dd9bb0283cdcd5a512a2e8d5b
0xc73cd8f0f011d46f0076bc857daf7a8bfb87ed99
0xdfa2b048f97875ec71332146392a41f18ba8d53b
0x06d2ca17f1ecdc511f6a8f012031497d15ffa7b5
0x8ebd93df888dc24646b916d3f95eb779c0c161c8
0x66552c8f0b7de901403c4934a8d46907d4a052c3
0xcefd53829916756faa8fea60ea6de0103cf56b31
0xe73f0f6ec79eace728b90eaf95634b84684117f0
0x08720736fddd2180e0920810499ba40e1c0686ea
0x7acd37370b7881be58b60cddc7efdd7fd911cde1
0x6f26f5fb6b6a1099ff181f0a637cbed4ce6a3a5f
0x920c7de817795fbe2da01692a6e403613a03a413
0xeb71b0d93ee03d5a7d51af6ece88d252040db2e1
0x7d342bac841a3e28534c16de827b2889e91bd4ae
0x69acea61fc87923cd06e937abdae6b5a82ec3e61
0x4286defd2646648738f288a5889c69a5baae2526
0xd5e0cb9051cf15ca3207b0b02ca13395a0d2419d
0x6b0817a73db7340f766d6ab687a364c468114c13
0x76bb1671ba21fdbe9f29cbf56f7dfad585756b7e
0xdcbf64a28fca08f3a762a06dccf75969d68992b5
# Reasoning
there are multiple matic and usdc transfers between addresses, most of the addresses are not actively used and do not contain value
# My Address (Optional)
0x5f2CBC511eF0a92a473943672a7a97028ABaBC29

**Comment by louie-ml** [comment]
Thank you for your report @okkux. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows a strong bond between the listed addresses.
![image](https://user-images.githubusercontent.com/80497604/226060960-4242af81-3818-406b-949d-81353872114e.png)

The following 22 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0x22a5ccd63f2c9910ef170a0ddee2688f9c792e3c
0x320b18b84fc5452045fc3e01ed4b748f4f31e477
0x9b8070918bc61903df86bd97e3820a003a2309f9
0x74cfa655e7f8d22dd9bb0283cdcd5a512a2e8d5b
0xc73cd8f0f011d46f0076bc857daf7a8bfb87ed99
0xdfa2b048f97875ec71332146392a41f18ba8d53b
0x06d2ca17f1ecdc511f6a8f012031497d15ffa7b5
0x8ebd93df888dc24646b916d3f95eb779c0c161c8
0x66552c8f0b7de901403c4934a8d46907d4a052c3
0xcefd53829916756faa8fea60ea6de0103cf56b31
0xe73f0f6ec79eace728b90eaf95634b84684117f0
0x08720736fddd2180e0920810499ba40e1c0686ea
0x7acd37370b7881be58b60cddc7efdd7fd911cde1
0x6f26f5fb6b6a1099ff181f0a637cbed4ce6a3a5f
0x920c7de817795fbe2da01692a6e403613a03a413
0xeb71b0d93ee03d5a7d51af6ece88d252040db2e1
0x7d342bac841a3e28534c16de827b2889e91bd4ae
0x69acea61fc87923cd06e937abdae6b5a82ec3e61
0x4286defd2646648738f288a5889c69a5baae2526
0xd5e0cb9051cf15ca3207b0b02ca13395a0d2419d
0x6b0817a73db7340f766d6ab687a364c468114c13
0x76bb1671ba21fdbe9f29cbf56f7dfad585756b7e
```

And the following 1 address will remain

`0xdcbf64a28fca08f3a762a06dccf75969d68992b5`
