### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by Dolphinseaa** [Increment-Finance/sybil-hunting#57]
# Sybil Addresses
0x158d38a669298cd7b1310629cd82939e80874c4e
0x9c9b14e6894754ef328e4271a37999431c3222fd
0x4618c7738aca938f897f2382fb0ab9fa80149d4f
0x353818f47223549a1e23b39022ccf9098db0ebfe
0xf245355f543dfe4a31d3446c545ea365e0c8ecce
0x0d6b28a88397a676ea3829c67055e23477581088
0x1e87f78ce5ff5af84758384784751db406b37309
0x58d5180b746a4d469d4c8b0562d9a6f9e8b6dede
0xf8a0d9886d910cdfd63ac8ed23f66cd9ec92f5db
0x483c98cfc03915cc3ac9ac8870663e4b32b35aea
0x15d9e4ae5595b1267f3057448172d1de525f627b
0x2cc30eae99fa85bad810091300b1214787cb0c35
0x81ce2e85d7d80071e9ee173baf82e5db31491872
# Reasoning

https://metasleuth.io/result/polygon/0x079c570abd04cc74a5a1c31d19c5d8f1e9255299?source=9e1d3917-002e-4ad9-b143-339a2d0ee856

Too many token transfers between addresses

# My Address (Optional)

0x42Ff6fDdeE32dc76D1698136bE86fe52b6505a09

**Comment by louie-ml** [comment]
Thank you for your report @Dolphinseaa. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows a strong bond between the listed addresses. 
![image](https://user-images.githubusercontent.com/80497604/226136046-bc4c8aeb-d411-4e00-b789-bcd258ea4697.png)


The following 12 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)
```
0x158d38a669298cd7b1310629cd82939e80874c4e
0x9c9b14e6894754ef328e4271a37999431c3222fd
0x4618c7738aca938f897f2382fb0ab9fa80149d4f
0x353818f47223549a1e23b39022ccf9098db0ebfe
0xf245355f543dfe4a31d3446c545ea365e0c8ecce
0x0d6b28a88397a676ea3829c67055e23477581088
0x1e87f78ce5ff5af84758384784751db406b37309
0x58d5180b746a4d469d4c8b0562d9a6f9e8b6dede
0xf8a0d9886d910cdfd63ac8ed23f66cd9ec92f5db
0x483c98cfc03915cc3ac9ac8870663e4b32b35aea
0x15d9e4ae5595b1267f3057448172d1de525f627b
0x2cc30eae99fa85bad810091300b1214787cb0c35
```

And the following 1 address will remain

`0x81ce2e85d7d80071e9ee173baf82e5db31491872`
