### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by Pars1907** [Increment-Finance/sybil-hunting#72]
# Sybil Addresses
0x3c8fc9e72a07fb7e799df00d598f28585996df07
0x4bca49f54ea1be1e44184c298816d90a1e595575
0x4a9ea24e0728cd40239bd25b3396c43b6c0bc188
0x04e220de16e568ec36d49845232537bc90ad4fe1
0x2ec0b62a65790fef1a0820a266970d58e9ba20f3
0x756535b61002c5f3d740711d20c30df93e50f2f3
0x4df179bd13d1afecb046c00f92003753a2ccadb8
0x107ce4547fff34e901337fe30febecd6dc421ec9
0x3f6bbb2dd1d3762ab69b36c9a32be0b0df551311
0x8f10e4388fe4c37f2cb3e6fca9f3023f21e383af
0x13c367d5456fa87e5487d96f1e7d2e3e1473534c
0xffebad9fafe863cfe2a243acc6062f45e0dde0b6
0xf59c9569d049fe6751fa355685533aa191cd2ea7
0x716687f2ac0b2610ee7c4fda3cff16d0a7bc658b
0x723ecdd7587d585b2a24e6053bc9a12fe1460edf
0xc09e6e1dffd669c94eb3c3385b58d4b8bd7040e9

# Reasoning
1- Too many token transfers between accounts.

# My Address (Optional)
0xdd1c32F78f45396877baA1AEe04f38575dD6a9B0

**Comment by louie-ml** [comment]
Thank you for your report @Pars1907. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows a strong bond between the listed addresses.
![image](https://user-images.githubusercontent.com/80497604/226145518-50302fa3-1d55-4cd6-aa13-624b9c45a9c8.png)

The following 15 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0x3c8fc9e72a07fb7e799df00d598f28585996df07
0x4bca49f54ea1be1e44184c298816d90a1e595575
0x4a9ea24e0728cd40239bd25b3396c43b6c0bc188
0x04e220de16e568ec36d49845232537bc90ad4fe1
0x2ec0b62a65790fef1a0820a266970d58e9ba20f3
0x756535b61002c5f3d740711d20c30df93e50f2f3
0x4df179bd13d1afecb046c00f92003753a2ccadb8
0x107ce4547fff34e901337fe30febecd6dc421ec9
0x3f6bbb2dd1d3762ab69b36c9a32be0b0df551311
0x8f10e4388fe4c37f2cb3e6fca9f3023f21e383af
0x13c367d5456fa87e5487d96f1e7d2e3e1473534c
0xffebad9fafe863cfe2a243acc6062f45e0dde0b6
0xf59c9569d049fe6751fa355685533aa191cd2ea7
0x716687f2ac0b2610ee7c4fda3cff16d0a7bc658b
0x723ecdd7587d585b2a24e6053bc9a12fe1460edf
```

And the following 1 address will remain

`0xc09e6e1dffd669c94eb3c3385b58d4b8bd7040e9`
