### ISSUE TITLE
Sybil Bounty Report

### ISSUE THREAD

**Issue by synxero354** [Increment-Finance/sybil-hunting#9]
# Sybil Addresses
0xcf1e5ad34db6a294920b11d81f70da0dcc323b82 (active on mainnet)
0x3ae6e955debc692699d8edbcdd80722893ac637a
0xe4a467b059fbab274ef597fd28576523f37f4175
0xe0e563b19f27cd1b2a787e50e110210d2419c9a2
0xbcabb5611e83374bc19b602ae06dac07bdbd4da1
0xcfb415118d6383d3f149679d94afc4e2c87a4234
0x333584a1eb0309675d4e6c8b2bf5888233cf2ed6
0xef4f4c94e2e6d2f89d0651e20d8e732d97684609

# Reasoning
1) Address 0x3aE6e955DEbC692699D8eDBCDD80722893AC637a distributed test eth to all other addreses that have no other activity other than testing. https://goerli.etherscan.io/address/0x3ae6e955debc692699d8edbcdd80722893ac637a
2) All addresses only have one POAP activity.

# My Address (Optional)
0xfb15339d187A76AF62698F73D700E1F8536f03BD

**Comment by louie-ml** [comment]
Thank you for your report @synxero354. The following visualizer from [Arkham](https://platform.arkhamintelligence.com/) shows the path of these transfers on Ethereum mainnet.
![image](https://user-images.githubusercontent.com/80497604/220151890-b5314f31-1379-45f8-a262-d32085bd1abe.png)

We can't really see much from the above but after digging into your reasoning more, we can see a better picture on goerli testnet. The inital inflow of test ETH came from 0xcf1e5ad34db6a294920b11d81f70da0dcc323b82 and transferred to 0x3ae6e955debc692699d8edbcdd80722893ac637a.
![image](https://user-images.githubusercontent.com/80497604/220152558-cf749e15-36ef-4460-8ded-9d9efe371c51.png)

Then, as you stated, 0x3ae6e955debc692699d8edbcdd80722893ac637a distributed test tokens to all the other listed addresses, which is sufficient to state that this is a valid report.
![image](https://user-images.githubusercontent.com/80497604/220153391-c2a18d6b-8338-4fe0-bb37-ded54bf77347.png)

The following 7 addresses will be removed from the [full address list](https://docs.google.com/spreadsheets/d/1Y1ax3pePYNKpU4L9WbZOcv3QGbz6LlRdzE-AkkaeAeM/edit#gid=1556209484&range=A1)

```
0x3ae6e955debc692699d8edbcdd80722893ac637a
0xe4a467b059fbab274ef597fd28576523f37f4175
0xe0e563b19f27cd1b2a787e50e110210d2419c9a2
0xbcabb5611e83374bc19b602ae06dac07bdbd4da1
0xcfb415118d6383d3f149679d94afc4e2c87a4234
0x333584a1eb0309675d4e6c8b2bf5888233cf2ed6
0xef4f4c94e2e6d2f89d0651e20d8e732d97684609
```

And the following 1 address will remain

`0xcf1e5ad34db6a294920b11d81f70da0dcc323b82`
